version: "3.8"

# All services:
services:

  # API Service (Backend):
  api-service:

    # Image name:
    image: gyratinggyraffe/red-cardinal-full:1.1

    # Where is the docker file location:
    build: ./Backend

    # Container name:
    container_name: red-cardinal-full

    # Port binding (host:container):
    ports:
      - 80:4000

    # On crash - what to do (restart unless stopped manually):
    restart: unless-stopped

    # Environment variables:
    environment:
      - MYSQL_HOST=red-cardinal-db.cofv2mnqsrbd.eu-north-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASENAME=vacations-db
      - NODE_ENV=production
      - PORT=4000
      - HOST=localhost
      - ORIGIN=http://localhost
      - IMG_URL=api/images

# ----------------------------------------------------------------------------------------------------

volumes:
  red-cardinal: