version: "3.8"

# All services:
services:

  # App Service (Full stack, statics served by backend):
  app-service:

    # Image name:
    image: gyratinggyraffe/red-cardinal-full:1.1

    # Where is the docker file location:
    build: ./app

    # Container name:
    container_name: red-cardinal-full

    # Port binding (host:container):
    ports:
      - 80:4000

    # On crash - what to do (restart unless stopped manually):
    restart: unless-stopped

# ----------------------------------------------------------------------------------------------------

volumes:
  red-cardinal: